version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=961553472565.dkr.ecr.us-east-1.amazonaws.com/sm-email-service:latest
      - PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[",]//g' | sed 's/version://g' | tr -d '[[:space:]]')
      - echo $PACKAGE_VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Building compilation container for api...
      - chmod +x entrypoint.sh
      - docker build -t sm-email-service .
      - docker tag sm-email-service:latest $REPOSITORY_URI:$PACKAGE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$PACKAGE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"api","imageUri":"%s"}]' $REPOSITORY_URI:$PACKAGE_VERSION > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
